scheduleC ={
    '8': ['Advertising','Publicidad','Todo gasto relacionado con la publicidad de la empresa o rotulos del camión o de la camioneta del trabajo '],
    '9':['Car and Truck Expenses','Gastos de vehículos','54.5 centavos por milla que se utilizó el vehículo - no se requiere guardar los comprobantes de combustible ni aceite, pero se debe generar una vitacora del uso del vehículo.  Se le agrega el costo de estacionamientos o carreteras de cuota.      La segunda opción es llevar control de todos los gastos del vehículo.  Todos los gastos relacionados con el Camión, aceite, anticongelante, liquido de frenos, baterias, partes, reparaciones, mejoras, estacionamiento del vehículo, cuotas de carreteras, TODO.'],
    '10': ['Commissions and fees', 'Comisiones y honorarios', 'Comisiones u honorarios que se pagó a terceros para el debido funcionamiento del negocio. '],
    '11':['Contract labor','Trabajo contratado','Si se obtuvo algún ingreso en el que se tuvo que contratar a terceros para ejecutarlo, se deduce lo que se le pagó a ese tercero.  Todos los que no sean tus trabajadores. '],
    '12':['Depletion','',''],
    '13':['Depreciation and section 179 expenses deduction','',''],
    '14':['Employee benefit programs, other than on line 19.','',''],
    '15':['Insurance (other than health)','Seguros (que no sean médicos)',''],
    '16a':['Mortgage interest-16a','intereses de hipotecas',''],
    '16b':['Other interest-16b','Intereses - Tarjetas de credito y otros',''],
    '17':['Legal and professional services','Servicios legales y profesionales','Costo de servicios profesionales para que funcione el negocio. '],
    '18':['Office expense (see instructions)','Gastos de oficina','Todos los gastos de la oficina, desde papel, libretas, lápices, calculadoras, tintas, impresoras, tijeras, TODO. '],
    '19':['Pention and profit-sharing plans','planes de pensiones y reparticion de utilidades',''],
    '20a':['Rent: Vehicles, machinery, and equipment','Renta de: Vehículos, maquinaria y equipo','Renta de maquinaria para dar servicio al Camión, para lavarlo, renta de traila para mover producto, etc. '],
    '20b':['Rent: Other business property','Renta: Otros bienes para el negocio','Renta de cualquier otra cosa para el negocio. - Oficina, storage, etc. '],
    '21':['Repairs and maintenance','Reparación y mantenimiento','todo servicio o reparación que NO SEA DEL CAMIÓN, ya todo lo del camión ser reporta en gastos de vehículo. '],
    '22':['Supplies (not included in Part III)','Consumibles','Cualquiero consumible no contemplado en otro apartado, como aroamtizantes para el camión, sabanas, cobijas, calentadores, etc. '],
    '23':['Taxes and licenses','Impuestos y licencias','Costo de licencias adquiridas e impuestos pagados.'],
    '24a':['Travel','Viajes','Todos los gastos relacionados con viajes fuera de casa que no se reportan en otros apartados, como hospedaje, pago para bañarse, solo del personal del negocio, no de los familiares o amigos.  NO INCLUYA ALIMENTOS NI PAGOS DE ESTACIONAMIENTO QUE SE AGREGARON EN GASTOS DEL VEHÍCULO. '],
    '24b':['Deductible meals (see instructions)-24b','alimentos deducibles','Registrar cada día que pasa fuera de casa más de un día ordianrio de trabajo.  2.  Necesita descansar para cumplir con la demanda del trabajo.'],
    '25':['Utilities','Servicios (basura, agua, luz, teléfono, internet, etc.)','Servicios que se pagan con el fin de cumplir con el negocio - no los de la casa o personales - aquí entra el celular. '],
    '26':['Wages (less employment credits)','Salarios','Solo si tienes trabajadores. '],
    '27a':['Other expenses (from line 48)','Otros gastos (de línea 48)','Cualquier otro gasto necesario para la operación del negocio y no esté contemplado en otro apartado. '],
    '27b':['Reserved for future use','Reservado para uso futuro',''],
}
