CREATE TABLE loads (
    id INT NOT NULL,
    idContracting INT,
    idHauling INT,
    idTruck INT, 
    idTrailer INT, 
    idDriver INT, 
    idClient INT, 
    idClientAgent INT, 
    contractDate DATE,
    referenceNo VARCHAR(255),
    rate  DECIMAL(13,2),
    amountPaid DECIMAL(13,2),
    datePaid DATE, 
    notes TEXT,
    delivered TINYINT(1),
    invoiced TINYINT(1),
    paid TINYINT(1),
    paidHCarrier TINYINT(1),
    completed TINYINT(1),
    PRIMARY KEY (id),
    FOREIGN KEY (idContracting) REFERENCES carriers(id),
    FOREIGN KEY (idHauling) REFERENCES carriers(id),
    FOREIGN KEY (idTruck) REFERENCES trucks(id),
    FOREIGN KEY (idTrailer) REFERENCES trailers(id),
    FOREIGN KEY (idDriver) REFERENCES drivers(id),
    FOREIGN KEY (idClient) REFERENCES clients(id),
    FOREIGN KEY (idClientAgent) REFERENCES clients_agents(id)
    )
ENGINE = InnoDB;